{"name": "test_add[add-other]", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'qqqq' == 'qq'\n  - qq\n  + qqqq", "trace": "self = <test_pytest.homework.test_calc_new.TestCalc object at 0x000002669600CB70>\nget_calc = <test_pytest.homework.calculator.Calculator object at 0x00000266960209E8>, get_add_datas = ['qq', 'qq', 'qq']\n\n    @pytest.mark.run(order=1)\n    def test_add(self, get_calc, get_add_datas):\n        # pass\n        result = None\n        try:\n            # 调用add函数,返回的结果保存在result里面\n            result = get_calc.add(get_add_datas[0], get_add_datas[1])\n            # 判断result结果是否等于期望的值\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_add_datas[2]\nE       AssertionError: assert 'qqqq' == 'qq'\nE         - qq\nE         + qqqq\n\ntest_calc_new.py:26: AssertionError"}, "parameters": [{"name": "get_add_datas", "value": "['qq', 'qq', 'qq']"}], "start": 1610804889418, "stop": 1610804889420, "uuid": "14821534-d3c8-4fa6-845f-f3c6f3820d21", "historyId": "86f74f09c13e04e57b4c6680cf86f748", "testCaseId": "9ad9766a0fb332026c77b44a1ef68af8", "fullName": "homework.test_calc_new.TestCalc#test_add", "labels": [{"name": "tag", "value": "run(order=1)"}, {"name": "parentSuite", "value": "homework"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-B1515VS"}, {"name": "thread", "value": "4300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "homework.test_calc_new"}]}