{"name": "test_mul[mul-other]", "status": "failed", "statusDetails": {"message": "AssertionError: assert None == 'ww'\n  +None\n  -'ww'", "trace": "self = <test_pytest_HT.test_calc_new.TestCalc object at 0x000001BF0F9332E8>\nget_calc = <test_pytest_HT.calculator.Calculator object at 0x000001BF0F87F1D0>, get_mul_datas = ['ww', 'ww', 'ww']\n\n    @pytest.mark.run(order=3)\n    def test_mul(self, get_calc, get_mul_datas):\n        result = None\n        try:\n            result = get_calc.mul(get_mul_datas[0], get_mul_datas[1])\n            if isinstance(result, float):\n                result = round(result, 2)\n        except Exception as e:\n            print(e)\n>       assert result == get_mul_datas[2]\nE       AssertionError: assert None == 'ww'\nE         +None\nE         -'ww'\n\ntest_calc_new.py:62: AssertionError"}, "parameters": [{"name": "get_mul_datas", "value": "['ww', 'ww', 'ww']"}], "start": 1610373753635, "stop": 1610373753635, "uuid": "f8a2138b-73db-470b-adf5-c5d617c6ec9d", "historyId": "9e0165687ea221b7efe965a662e4960b", "testCaseId": "fe6bda14bd0e8d9a8af1eb7bd6c20851", "fullName": "test_calc_new.TestCalc#test_mul", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "DESKTOP-B1515VS"}, {"name": "thread", "value": "3300-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}